### ISSUE TITLE
Create a new icon

### ISSUE THREAD

**Issue by cjfloss** [cjfloss/envelope#2]

**Comment by cjfloss** [comment]
Some ideas http://appcrawlr.com/ios-apps/best-apps-envelope-budgeting

**Comment by cjfloss** [comment]
First trial
![01](https://user-images.githubusercontent.com/5838486/35181456-d04433d0-fda0-11e7-802e-4e40961309f8.png)

**Comment by cjfloss** [comment]
Second Trial
![02](https://user-images.githubusercontent.com/5838486/35181465-ed27aebe-fda0-11e7-8a26-4d755bb21831.png)

**Comment by cjfloss** [comment]
### Third Trial
![03](https://user-images.githubusercontent.com/5838486/35181476-0860611c-fda1-11e7-8e81-29549d7605b5.png)

**Comment by cjfloss** [comment]
Fourth Trial
![t3](https://user-images.githubusercontent.com/5838486/35195955-1ed46204-feaa-11e7-8a95-1f2b1f63f3e2.png)

**Comment by Hedronmx** [comment]
Tried doing a new icon... Shadow is a bit off but I just wanted to sketch something
![Imgur](https://i.imgur.com/LnfYPXs.png)

**Comment by cjfloss** [comment]
The application has a new icon thanks to @Fatih20.
