### ISSUE TITLE
Can't Maximise the application

### ISSUE THREAD

**Issue by ar0ra1** [cjfloss/envelope#32]

**Comment by cjfloss** [comment]
I can't reproduce the issue.

Needs more information.

**Comment by ar0ra1** [comment]
Here : [Video](https://webmshare.com/EVmOy)

>Video will delete in 7 days

**Comment by cjfloss** [comment]
Your screen is smaller than 800 pixels which is envelope's window size.
It is fixed now.

Thanks for reporting!!

**Comment by ar0ra1** [comment]
Well 1366x768 is the default resolution for most of the laptops.
