### ISSUE TITLE
Check if the account still exists on startup

### ISSUE THREAD

**Issue by monsieurhannes** [cjfloss/envelope#38]
My (so far empty) envelope is missing the sidebar on the left. I don't know where it went and I have no clue how to get it back... Right now it's stuck in the Alcohol section... :D 

![screenshot from 2018-03-18 09 05 41](https://user-images.githubusercontent.com/20651440/37564133-d0223552-2a8f-11e8-94a9-afa67ac4ff40.png)

Any idea how to get it back to normal? I reinstalled it, but nothing changed.

A general thing: I don't really get some of the design. The left bar is clear to me, but when I want to add something it's not immediately clear that an entry was created. It might help to select the first cell automatically so you notice to type something there.

Anyway - I like the app and the idea and I hope to help at least with this report. I have no clue about programming though. Thanks for your work!

**Comment by cjfloss** [comment]
Sorry for taking so long to answer.

execute this in the terminal:
`gsettings reset com.github.cjfloss.envelope.settings selected-account-id`

it will reset the selected account in the configurations, and it should go back to normal!
---
