### ISSUE TITLE
Side bar is no more available!

### ISSUE THREAD

**Issue by alchehabi** [cjfloss/envelope#43]
For some reason the side bar isnt more available, i tried to uninstall the program and reinstall it. But the problem remained the same!

![envelope](https://user-images.githubusercontent.com/10380737/41781824-c150b5f4-7638-11e8-8c50-b367aa12b84e.png)

**Comment by cjfloss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ola](https://trello.com/c/8rtllm0W/1-ola)
